# Interactive component

Here is an interactive graph of Vaccination rate of different groups of people. 
You can click buttons to choose to see the comparison across different ethnicity groups and age groups.

We learned that `Hispanic/Latino` and `Black` ethnicity group and the age between `0-49` (especially children age <18) are falling behind.

<meta charset="utf-8">

<!-- Load d3.js -->
<script src="https://d3js.org/d3.v4.js"></script>

<!-- Add 2 buttons -->
<button onclick="update(data1)">Fully Vaccinated percent by ethnicity</button>
<button onclick="update(data2)">Fully Vaccinated percent by age group</button>

<!-- Create a div where the graph will take place -->
<div id="my_dataviz"></div>

<script>

// create 2 data_set
var data1 = [
   {group: "Hispanic/Latino", value: 	11.2},
   {group: "Black", value: 	12.2},
   {group: "Asian", value: 15.8},
   {group: "White", value: 19.5},
   {group: "American Indian", value: 27.9},
];

var data2 = [
   {group: "<18", value:0.5},
   {group: "18-29", value: 9.4},
   {group: "30-39", value: 11.4},
   {group: "40-49", value: 12.5},
   {group: "50-64", value: 27.4},
   {group: "65-74", value: 22.5},
   {group: "75+", value: 16.2}
];

// set the dimensions and margins of the graph
var margin = {top: 30, right: 30, bottom: 70, left: 60},
    width = 600 - margin.left - margin.right,
    height = 600 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

// Initialize the X axis
var x = d3.scaleBand()
  .range([ 0, width ])
  .padding(0.2);
var xAxis = svg.append("g")
  .attr("transform", "translate(0," + height + ")")

// Initialize the Y axis
var y = d3.scaleLinear()
  .range([ height, 0]);
var yAxis = svg.append("g")
  .attr("class", "myYaxis")


// A function that create / update the plot for a given variable:
function update(data) {

  // Update the X axis
  x.domain(data.map(function(d) { return d.group; }))
  xAxis.call(d3.axisBottom(x))

  // Update the Y axis
  y.domain([0, d3.max(data, function(d) { return d.value }) ]);
  yAxis.transition().duration(1000).call(d3.axisLeft(y));

  // Create the u variable
  var u = svg.selectAll("rect")
    .data(data)

  u
    .enter()
    .append("rect") // Add a new rect for each new elements
    .merge(u) // get the already existing elements as well
    .transition() // and apply changes to all of them
    .duration(1000)
      .attr("x", function(d) { return x(d.group); })
      .attr("y", function(d) { return y(d.value); })
      .attr("width", x.bandwidth())
      .attr("height", function(d) { return height - y(d.value); })
      .attr("fill", "#69b3a2")


  u
    .exit()
    .remove()
}

svg.append("text")
        .attr("x", (width / 2))             
        .attr("y", 0 - (margin.top / 2))
        .attr("text-anchor", "middle")  
        .style("font-size", "16px") 
        .style("text-decoration", "underline")  
        .text("Vaccination rate by ethnicity and age group");
        

        
// Initialize the plot with the first dataset
update(data1)

</script>